config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks/new', to: 'tasks#new'
  get 'index', to: 'tasks#index'
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    params[:id]
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to index_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :complete)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/all.html.erb
<h2>Todo list</h2>

<ul>
  <% @tasks.each do |task| %>
    <li>

      <% if task.completed? %>
        <input type="checkbox" checked>
      <% else %>
        <input type="checkbox">
      <% end %>

      <p style="display:inline">
        <%= task.title %>
      </p>
    </li>
  <% end %>
</ul>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h2>Todo list</h2>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed? %>
        <input type="checkbox" checked>
      <% else %>
        <input type="checkbox">
      <% end %>
      <%= link_to "#{task.title}", task_path(task) %>
    </li>
  <% end %>
</ul>

<%= link_to "+Create a new task", "/tasks/new" %>

app/views/tasks/new.html.erb
<p>im in the new</p>


<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

    <p>
      <%= @task.details %>
    </p>

<% if @task.completed? %>
  <input type="checkbox" checked>
  <p style="display:inline">This task is completed</p>
<% else %>
  <input type="checkbox" >
  <p style="display:inline">This task is not completed</p>
<% end %>

<div class="div">
  <%= link_to "Back to list", "/index" %>
</div>